---
title: "Songs Data"
author: "Dominique Lashley"
date: "2025-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
song_app_data <-
  most_streamed %>% 
  mutate(streams=as.numeric(streams, na.rm=T)) %>%
  group_by(track_name) %>% 
  summarize(total_streams=sum(streams),
            total_charts=sum(in_spotify_charts),
            total_playlists=sum(in_spotify_playlists))
```

```{r}
  
# Define UI
ui <- fluidPage(
    titlePanel("Top 10 Spotify Songs by Category"),
    
    selectInput("y", "Select Ranking Metric:",
                choices = c("Most Streams" = "total_streams",
                            "Most Songs on Charts" = "total_charts",
                            "Most Songs in Playlists" = "total_playlists"),
    selected="total_streams"),
    
 plotOutput("plot")
)


server <- function(input, output, session) {
  
  
  
  output$plot <- renderPlot({
    top_songs <- song_app_data %>%
            arrange(desc(!!sym(input$y))) %>%  # Sort by selected metric
            head(10)
    
    
    ggplot(data=top_songs, 
           aes_string(x="`track_name`", y=input$y))+
      geom_col(fill = "#1DB954")+
      coord_flip()+
      labs(x="Song", y="Metric")+
      theme_classic()
})
}

shinyApp(ui, server)

```